"""File table

Revision ID: 84fedbfb17ed
Revises: 8d1bafb286ae
Create Date: 2020-04-23 17:48:08.066426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fedbfb17ed'
down_revision = '8d1bafb286ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('relative_path', sa.String(length=300), nullable=True),
    sa.Column('reclamation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reclamation_id'], ['reclamation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
